[tool.poetry]
name = "silicon-notes"
version = "0.1.2"
description = "A personal knowledge base with a wiki-like interface."
authors = ["Charles Ulrich <charles.silicon@bityard.net>"]
repository = "https://github.com/cu/silicon"
readme = "README.md"
packages = [
    { include = "silicon" },
]

[tool.poetry.dependencies]
python = "^3.9"
Flask = "^2.3.0"
mistune = "^3.0.2"
Pygments = "^2.6.1"
python-slugify = "^8.0.0"
python-dotenv = "^1.0.0"
gunicorn = "^21.1.0"

[tool.poetry.group.dev.dependencies]
watchdog = "^3.0.0"
pytest = "^7.2.0"
beautifulsoup4 = "^4.11.1"
flake8 = "^6.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
