[tool.poetry]
name = "notes"
version = "0.1.0"
description = "A personal knowledge base with a wiki-like interface."
authors = ["Charles Ulrich <charles.silicon@bityard.net>"]

[tool.poetry.dependencies]
python = "^3.9"
Flask = "^2.0.2"
mistune = "^2.0.2"
Pygments = "2.6.1"
python-slugify = "^4.0.0"
python-dotenv = "^0.13.0"
gunicorn = "^20.1.0"

[tool.poetry.dev-dependencies]
watchdog = "^2.1.6"
pytest = "^6.2.5"
beautifulsoup4 = "^4.10.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
