name: Build and push tagged container image

on:
  push:
    tags: ['*']

env:
  REPO: silicon

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_NAMESPACE }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE}}/${{ env.REPO }}:latest
            ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE}}/${{ env.REPO }}:${{ github.ref_name }}
